#!/bin/bash

set -e

echo
echo "===> Build started at $(date)"
echo
START=$SECONDS

# Unconditionally print elapsed build time at exit
function finish {
  echo "===> Elapsed time: $(($SECONDS - $START)) seconds"
}
trap finish EXIT

echo "---> Preparing source..."
mkdir -p $SOURCE

cp -Rf /tmp/src/. $SOURCE

cd $SOURCE

# echo "---> Downloading dependencies..."
#go get -v ./...

echo "---> Enable GOMOD"
export GO111MODULE=on
go mod init .

echo "---> Building application source..."
#go build -v -o main
#go install main

CGO_ENABLED=0 GOOS=linux go build -v -a -installsuffix cgo -o main . && \
upx --ultra-brute -qq topz && \
upx -t topz

echo
echo "===> Build completed at $(date)"

# Fix source directory permissions
fix-permissions ./
