#!/bin/bash
set -e

echo
echo "===> Build started at $(date)"
echo
START=$SECONDS

# Unconditionally print elapsed build time at exit
function finish {
  echo "===> Elapsed time: $(($SECONDS - $START)) seconds"
}
trap finish EXIT

echo "---> Preparing source..."
mkdir -p $SOURCE

cp -Rf /tmp/src/. $SOURCE

cd $SOURCE

pwd

# echo "---> Downloading dependencies..."
#go get -v ./...

GO111MODULE=${GO111MODULE:-on}
CGO_ENABLED=${CGO_ENABLED:-0}
GOOS=${GOOS:-linux}

# Raspberry PI 3 ARM GOOS=linux GOARCH=arm GOARM=7 go build  -o main_arm main.go


ARTIFACT=${ARTIFACT:-"${GOBIN}/main"}

BUILDOPTION_default="-v -a -installsuffix cgo "
BUILDOPTION=${BUILDOPTION:-$BUILDOPTION_default}

echo "** GO build options **"
echo "============================================="
echo "|| GO111MODULE: $GO111MODULE"
echo "|| CGO_ENABLED: $CGO_ENABLED"
echo "|| GOOS: $GOOS"
echo "|| GOBIN: $GOBIN"
echo "|| BUILDOPTION: $BUILDOPTION"
echo "||"
echo "|| ARTIFACT: $ARTIFACT"
echo "============================================="

if [ ! -f "go.mod" ]; then
echo "---> No go Mod found we Enable GOMOD"
export GO111MODULE=on
go mod init .
fi

if [  -f "go.sum" ]; then
echo "--> find go.sum file enable gomod..."
export GO111MODULE=on
fi

echo "---> Building application source..."
#go build -v -o main
#go install main

go build ${BUILDOPTION} -o ${ARTIFACT} main.go
  ERR=$?
  if [ $ERR -ne 0 ]; then
    echo "Aborting due to error code $ERR from $BUILDOPTION"
    exit $ERR
  fi
echo "---> Building finish"

#echo "install binary"
#go install -v main.go

echo
echo "---> upx compress "
upx -qq ${ARTIFACT}
echo "---> upx verify "
upx -t ${ARTIFACT}
#upx --ultra-brute -qq main && \

echo
pwd
chmod +x ${ARTIFACT}
du -hs ${ARTIFACT}
ls -lahrt ${GOBIN}

echo
echo "===> Build completed at $(date)"

# Fix source directory permissions
echo "---> fix-permissions"
fix-permissions ${ARTIFACT}
#fix-permissions ./
