#!/bin/sh

IMAGEVER=$($GO_VERSION | sed s/\.//)

cat <<EOF
This is a S2I Go $GO_VERSION CentOS base image:
To use it, install S2I: https://github.com/openshift/source-to-image

Sample invocation:

$ s2i build  https://github.com/bigg01/go-s2i-centos7.git --context-dir test-app --ref master bigg01/go-s2i-centos7 go-test-app

You can then run the resulting image via:

$ docker run -p 8080:8080 go-test-app

#localtest
docker build -t bigg01_local/go-s2i-centos7 .
s2i build test-app/ bigg01_local/go-s2i-centos7 test
EOF
